matrix:
  include:
    - language: node_js
      node_js: '8'
      cache:
        directories:
          - 'node_modules'

    - language: python
      python:
        - "3.6"
      services:
        - docker
      before_install:
        - cd claims-related
        - docker-compose build data-analysis
      install: true
      script:
        - make test
